Fix compilation error when adding header file "wl.h" to "h264-to-file/main.c"
This commit fixes the below compilation error when header file "wl.h" is
included in "h264-to-file/main.c":

  | user@ubuntu:~/camera-image-overlay$ make
  | install -m 664 common/ttf/LiberationSans-Regular.ttf h264-to-file/LiberationSans-Regular.ttf
  | install -m 664 common/ttf/LiberationSans-Regular.ttf raw-video-to-lcd/LiberationSans-Regular.ttf
  | mkdir -p objs/h264-to-file/
  | aarch64-poky-linux-gcc  -mtune=cortex-a55 -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat   \
  | -Wformat-security -Werror=format-security --sysroot=/path/to/sdk/sysroots/aarch64-poky-linux -Wall \
  | -Wextra -Werror -I./common/inc -I/path/to/sdk/sysroots/aarch64-poky-linux/usr/include/freetype2    \
  | -I/path/to/sdk/sysroots/aarch64-poky-linux/usr/include/libpng16 -c h264-to-file/main.c             \
  | -o objs/h264-to-file/main.o
  |
  | In file included from h264-to-file/main.c:19:
  | ./common/inc/wl.h:28:10: fatal error: xdg-shell-client-protocol.h: No such file or directory
  |  #include "xdg-shell-client-protocol.h"
  |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | compilation terminated.
  | make: *** [Makefile:63: objs/h264-to-file/main.o] Error 1

Without this patch, Makefile will compile "h264-to-file/main.c" before
other common source files, such as: egl.c, gl.c, mmngr.c, omx.c, queue.c,
ttf.c, util.c, v4l2.c, wl.c, and xdg-shell-protocol.c (generated).

If header file "xdg-shell-client-protocol.h" does not exist and users
include "wl.h" (which included "xdg-shell-client-protocol.h") in
"h264-to-file/main.c", the above compilation error will happen.

Therefore, to fix this issue, we must explicitly tell Makefile to generate
and compile all common source files before compiling sample apps, such as:
"h264-to-file/main.c" and "raw-video-to-lcd/main.c".

Signed-off-by: Loc Pham <loc.pham.xh@rvc.renesas.com>